### ISSUE TITLE
for recurring jobs, when new results are available the screen sometimes goes blank

### ISSUE THREAD

**Issue by rbjo** [equinor/forecast-of-response-dmt#213]
Described in the email from Tim:

![image](https://user-images.githubusercontent.com/57898762/149903826-833afedd-3877-4120-9048-8f4e6ddc03d3.png)

![image](https://user-images.githubusercontent.com/57898762/149903919-96f55f2e-ecd2-40d3-adb9-f0ea8c5cfd4d.png)

**Comment by Timothy-Edward-Kendon** [comment]
If you delete the plots, you can plot new results. This issue is therefore associated with [Issue 214](https://github.com/equinor/forecast-of-response-dmt/issues/214).
